/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCard: typeof import('./components/AddCard.vue')['default']
    AddDeck: typeof import('./components/AddDeck.vue')['default']
    CardHolder: typeof import('./components/CardHolder.vue')['default']
    CardManager: typeof import('./components/CardManager.vue')['default']
    CardUI: typeof import('./components/CardUI.vue')['default']
    DeckHolder: typeof import('./components/DeckHolder.vue')['default']
    FlashCard: typeof import('./components/FlashCard.vue')['default']
    PlayWrong: typeof import('./components/PlayWrong.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
